version: '3.8'
services:
  web:
    image: node:18-alpine
    container_name: nextjs-prod
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/app
      - /app/node_modules
    command: sh -c "yarn install --frozen-lockfile && yarn build && yarn start"
